const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';
const SWITCH_ORDER_DETAILS_MODAL_STATE = 'SWITCH_ORDER_DETAILS_MODAL_STATE';

export {
  PLACE_ORDER_REQUEST,
  PLACE_ORDER_SUCCESS,
  PLACE_ORDER_FAILED,
  SWITCH_ORDER_DETAILS_MODAL_STATE,
}